version: "3.7"

services:
  app:
    build: .
    image: decentralize/postgres-backup:0.2.0
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db
      - RCLONE_CONFIG_MYS3_TYPE=s3
      - RCLONE_S3_PROVIDER=Minio
      - RCLONE_CONFIG_MYS3_ACCESS_KEY_ID=minioadmin
      - RCLONE_CONFIG_MYS3_SECRET_ACCESS_KEY=minioadmin
      - RCLONE_CONFIG_MYS3_ENDPOINT=http://minio:9000
      - RCLONE_TARGET=mys3:backup

      # secret key: AGE-SECRET-KEY-1P6TMQJ780M53NQHJ56Q47EXF504NWNGMKF6F5ZR8WKCDY5ZGQ0JSUN4SQU
      - RECIPIENT=age17mcyt34uwq42j2s708uur4dqkt4dv3tr5jp2gmr9zpqnvc2gs3csqq0cud

      # optional
      # - HEALTHCHECKS_URL=https://healthchecks.example.com/ping/8382dda-5d12-475c-bd16-17a0a975e11d
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres

  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000/tcp
      - 9001:9001/tcp
